version: '3.7'
services:
  postgres:
    image: postgres:14.5
    command: postgres -c 'max_connections=200'
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - ./.PG_DATA:/var/lib/postgresql/data
